Repository StanislavYurchenko/easy-library, pull requests merged in 2023-02, with the labels that each got.

#6 3 feature create books. Refactoring structure`s folder
  apps/server-nest/src/app/app.config.ts
  apps/server-nest/src/app/app.module.ts
  apps/server-nest/src/app/configs/index.ts
  apps/server-nest/src/app/configs/schema.config.ts
  apps/server-nest/src/app/controller/index.ts
  apps/server-nest/src/app/controller/user/user.controller.spec.ts
  apps/server-nest/src/app/dto/index.ts
  apps/server-nest/src/app/modules/books/books.module.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.spec.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.ts
  apps/server-nest/src/app/modules/books/controller/index.ts
  apps/server-nest/src/app/modules/books/dto/create-book.dto.ts
  apps/server-nest/src/app/modules/books/dto/index.ts
  apps/server-nest/src/app/modules/books/dto/update-book.dto.ts
  apps/server-nest/src/app/modules/books/index.ts
  apps/server-nest/src/app/modules/books/interface/books.interface.ts
  apps/server-nest/src/app/modules/books/interface/index.ts
  apps/server-nest/src/app/modules/books/schema/book.schema.ts
  apps/server-nest/src/app/modules/books/schema/index.ts
  apps/server-nest/src/app/modules/books/service/books.service.spec.ts
  apps/server-nest/src/app/modules/books/service/books.service.ts
  apps/server-nest/src/app/modules/books/service/index.ts
  apps/server-nest/src/app/modules/index.ts
  apps/server-nest/src/app/modules/user/controller/index.ts
  apps/server-nest/src/app/modules/user/controller/user.controller.ts
  apps/server-nest/src/app/modules/user/dto/create-user-dto.ts
  apps/server-nest/src/app/modules/user/dto/index.ts
  apps/server-nest/src/app/modules/user/dto/update-user-dto.ts
  apps/server-nest/src/app/modules/user/index.ts
  apps/server-nest/src/app/modules/user/interface/index.ts
  apps/server-nest/src/app/modules/user/interface/user.interface.ts
  apps/server-nest/src/app/modules/user/schema/index.ts
  apps/server-nest/src/app/modules/user/schema/user.schema.ts
  apps/server-nest/src/app/modules/user/service/index.ts
  apps/server-nest/src/app/modules/user/service/user.service.ts
  apps/server-nest/src/app/modules/user/user.module.ts
  apps/server-nest/src/app/service/index.ts
  apps/server-nest/tsconfig.app.json
  libs/api-interface/book.interface.ts
  libs/api-interface/index.ts
  package.json
  tsconfig.base.json
Labels: done

#7 9-config: Eslint config
  .eslintrc.json
  .github/workflows/lint.yml
  .prettierrc
  apps/client-angular/src/app/app.component.spec.ts
  apps/client-angular/src/app/app.component.ts
  apps/client-angular/src/app/app.module.ts
  apps/client-angular/src/main.ts
  apps/server-nest/src/app/app.config.ts
  apps/server-nest/src/app/app.controller.spec.ts
  apps/server-nest/src/app/app.module.ts
  apps/server-nest/src/app/app.service.spec.ts
  apps/server-nest/src/app/configs/index.ts
  apps/server-nest/src/app/configs/schema.config.ts
  apps/server-nest/src/app/modules/books/books.module.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.spec.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.ts
  apps/server-nest/src/app/modules/books/dto/create-book.dto.ts
  apps/server-nest/src/app/modules/books/interface/books.interface.ts
  apps/server-nest/src/app/modules/books/schema/book.schema.ts
  apps/server-nest/src/app/modules/books/service/books.service.ts
  apps/server-nest/src/app/modules/user/controller/user.controller.ts
  apps/server-nest/src/app/modules/user/dto/create-user-dto.ts
  apps/server-nest/src/app/modules/user/index.ts
  apps/server-nest/src/app/modules/user/interface/user.interface.ts
  apps/server-nest/src/app/modules/user/schema/user.schema.ts
  apps/server-nest/src/app/modules/user/service/user.service.ts
  apps/server-nest/src/app/modules/user/user.module.ts
  apps/server-nest/src/main.ts
  package-lock.json
  package.json
  tsconfig.base.json
  tsconfig.json
Labels: in progress

#10 9-feature: Rafactor AppModule and DbModule
  apps/server-nest/src/app/app.module.ts
  apps/server-nest/src/app/db/db.config.ts
  apps/server-nest/src/app/db/db.module.ts
  apps/server-nest/src/app/db/index.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.spec.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.ts
  apps/server-nest/src/app/modules/user/controller/users.controller.ts
  apps/server-nest/src/main.ts
  libs/api-interface/constance.ts
  libs/api-interface/index.ts
  tsconfig.base.json
Labels: feature, done

#12 hotfix ComfigModule import into AppModule
  .github/workflows/ci.yml
  README.md
  apps/server-nest/src/app/app.module.ts
  apps/server-nest/src/app/db/db.module.ts
Labels: done

#16 17-feature: Add hashing password
  apps/server-nest/src/app/app.controller.ts
  apps/server-nest/src/app/modules/auth/auth.module.ts
  apps/server-nest/src/app/modules/auth/controller/auth.controller.ts
  apps/server-nest/src/app/modules/auth/interface/auth.interface.ts
  apps/server-nest/src/app/modules/auth/service/auth.service.ts
  apps/server-nest/src/app/modules/auth/strategy/jwt.strategy.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.ts
  apps/server-nest/src/app/modules/reviews/controller/reviews.controller.ts
  apps/server-nest/src/app/modules/users/controller/users.controller.ts
  apps/server-nest/src/app/modules/users/dto/create-user-dto.ts
  apps/server-nest/src/app/modules/users/interface/user.interface.ts
  apps/server-nest/src/app/modules/users/schema/user.schema.ts
  apps/server-nest/src/app/modules/users/service/users.service.ts
  package-lock.json
  package.json
Labels: done

#17 18-feature: Exclude passport from Users table responce
  apps/server-nest/src/app/modules/auth/service/auth.service.ts
  apps/server-nest/src/app/modules/auth/strategy/jwt.strategy.ts
  apps/server-nest/src/app/modules/users/schema/user.schema.ts
  apps/server-nest/src/app/modules/users/service/users.service.ts
Labels: feature, done

#18 8-feature: Init swagger
  README.md
  apps/server-nest/src/app/libs/enum.ts
  apps/server-nest/src/app/libs/validate/email.validate.ts
  apps/server-nest/src/app/modules/auth/controller/auth.controller.spec.ts
  apps/server-nest/src/app/modules/auth/controller/auth.controller.ts
  apps/server-nest/src/app/modules/auth/dto/login-dto.ts
  apps/server-nest/src/app/modules/auth/interface/auth.interface.ts
  apps/server-nest/src/app/modules/auth/service/auth.service.ts
  apps/server-nest/src/app/modules/auth/strategy/jwt.strategy.spec.ts
  apps/server-nest/src/app/modules/auth/strategy/local.strategy.spec.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.ts
  apps/server-nest/src/app/modules/books/dto/create-book.dto.ts
  apps/server-nest/src/app/modules/books/dto/update-book.dto.ts
  apps/server-nest/src/app/modules/reviews/controller/reviews.controller.ts
  apps/server-nest/src/app/modules/reviews/dto/create-review.dto.ts
  apps/server-nest/src/app/modules/reviews/dto/update-review.dto.ts
  apps/server-nest/src/app/modules/users/controller/users.controller.ts
  apps/server-nest/src/app/modules/users/dto/create-user-dto.ts
  apps/server-nest/src/app/modules/users/dto/update-user-dto.ts
  apps/server-nest/src/app/modules/users/interface/user.interface.ts
  apps/server-nest/src/app/modules/users/service/users.service.ts
  apps/server-nest/src/main.config.ts
  apps/server-nest/src/main.ts
  libs/api-interface/common.interface.ts
  libs/api-interface/constance.ts
  package-lock.json
  package.json
Labels: feature, in progress

#19 20-feature: Push/Pull user into list
  apps/server-nest/src/app/modules/auth/auth.module.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.ts
  apps/server-nest/src/app/modules/books/dto/update-book-user-id-list.dto.ts
  apps/server-nest/src/app/modules/books/interface/book.interface.ts
  apps/server-nest/src/app/modules/books/service/books.service.ts
  apps/server-nest/src/app/modules/reviews/controller/reviews.controller.ts
  apps/server-nest/src/app/modules/reviews/dto/update-review-user-id-list.dto.ts
  apps/server-nest/src/app/modules/reviews/interface/review.interface.ts
  apps/server-nest/src/app/modules/reviews/service/reviews.service.ts
  libs/api-interface/constance.ts
Labels: feature, done

#22 7 feature error handler
  apps/server-nest/src/app/app.module.ts
  apps/server-nest/src/app/libs/filters/extended-exception.filter.ts
  apps/server-nest/src/app/modules/auth/controller/auth.controller.ts
  apps/server-nest/src/app/modules/auth/interface/auth.interface.ts
  apps/server-nest/src/app/modules/auth/service/auth.service.ts
  apps/server-nest/src/app/modules/books/controller/books.controller.ts
  apps/server-nest/src/app/modules/reviews/controller/reviews.controller.ts
  apps/server-nest/src/app/modules/users/controller/users.controller.ts
  apps/server-nest/src/app/modules/users/service/users.service.ts
  apps/server-nest/src/main.ts
  libs/api-interface/common.interface.ts
Labels: feature, done
